### ISSUE TITLE
Update Stacked Services to ^0.5.4+2

### ISSUE THREAD

**Issue by rexthecoder** [YazeedAlKhalaf/Stacked#2]
It is tend that stack services has been updated therefore the older version in this project throws error with the new flutter update

**Comment by YazeedAlKhalaf** [comment]
Thanks for your notice! I will be updating it asap 👍✨

**Comment by YazeedAlKhalaf** [comment]
@Rexfordasamoah51 

I have released a new version, [v2.1.0](https://marketplace.visualstudio.com/items?itemName=YazeedAlKhalaf.stacked), it fixes the issue you noted and adds a lot of cool changes that you will like!

I feel safe to close this issue, if you have any reasons to re-open it please comment down with the reason.

Thanks and Stay Safe ✨

**Comment by rexthecoder** [comment]
Amazing work done. I will contribute to this your project later on. Well done for the good job 👍
